---

data_center_name: Default
storage_name: stfdal1003
cluster_description: OCP
cluster_name: Default
ocp_network_prefix: "ovn-vmnet"
ocp_network_count: 8
ocp_network_start: 10
mgmt_network: ovirtmgmt
template_name: centos-7

engine_fqdn: rhv-admin.cicd.red-chesterfield.com
mgmt_boot_protocol: static
external_address: 169.48.172.178
external_netmask: 255.255.255.240
external_gateway: 169.48.172.177
external_hostname: rhv-proxy-vm.cicd.red-chesterfield.com

base_domain: cicd.red-chesterfield.com
#ocp_dns: true
ocp_network_profile: ovn-vmnet-10
ocp_networks:
- nic: net0
  name: net-10
  dhcp_range: 192.168.210.101,192.168.210.150,5m
  address: 192.168.210.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.210.32
  api_internal_address: 192.168.210.30
  api_fqdn: api.rhv-cluster-01.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-01.cicd.red-chesterfield.com
- nic: net1
  name: net-11
  dhcp_range: 192.168.211.101,192.168.211.150,5m
  address: 192.168.211.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.211.32
  api_internal_address: 192.168.211.30
  api_fqdn: api.rhv-cluster-01.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-01.cicd.red-chesterfield.com
- nic: net2
  name: net-12
  dhcp_range: 192.168.212.101,192.168.212.150,5m
  address: 192.168.212.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.212.32
  api_internal_address: 192.168.212.30
  api_fqdn: api.rhv-cluster-02.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-02.cicd.red-chesterfield.com
- nic: net3
  name: net-13
  dhcp_range: 192.168.213.101,192.168.213.150,5m
  address: 192.168.213.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.213.32
  api_internal_address: 192.168.213.30
  api_fqdn: api.rhv-cluster-03.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-03.cicd.red-chesterfield.com
- nic: net4
  name: net-14
  dhcp_range: 192.168.214.101,192.168.214.150,5m
  address: 192.168.214.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.214.32
  api_internal_address: 192.168.214.30
  api_fqdn: api.rhv-cluster-04.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-04.cicd.red-chesterfield.com
- nic: net5
  name: net-15
  dhcp_range: 192.168.215.101,192.168.215.150,5m
  address: 192.168.215.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.215.32
  api_internal_address: 192.168.215.30
  api_fqdn: api.rhv-cluster-05.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-05.cicd.red-chesterfield.com
- nic: net6
  name: net-16
  dhcp_range: 192.168.216.101,192.168.216.150,5m
  address: 192.168.216.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.216.32
  api_internal_address: 192.168.216.30
  api_fqdn: api.rhv-cluster-06.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-06.cicd.red-chesterfield.com
- nic: net7
  name: net-17
  dhcp_range: 192.168.217.101,192.168.217.150,5m
  address: 192.168.217.1
  netmask: 255.255.255.0
  router_internal_address: 192.168.217.32
  api_internal_address: 192.168.217.30
  api_fqdn: api.rhv-cluster-07.cicd.red-chesterfield.com
  apps_fqdn: apps.rhv-cluster-07.cicd.red-chesterfield.com

